server:
  port: 1103
spring:
  application:
    name: eureka-security-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://stellagosa:123456@localhost:1004/eureka/