server:
  port: 1001
spring:
  application:
    name: server-demo
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/minio-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 1GB

minio:
  config:
    endpoint: http://localhost
    port: 9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: demo-test
