server:
  port: 8989
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t_crud?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  messages:
    encoding: utf-8
    basename: i18n/login
  thymeleaf:
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:com/stellagosa/demo/curd/mapper/*.xml
  type-aliases-package: com.stellagosa.demo.curd.entity