server:
  port: 2001
spring:
  application:
    name: ribbon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1001/eureka/ # eureka注册中心

service-url:
  user-service: http://user-service
